IF OBJECT_ID('dbo.COBRANZA_ASIGNACIONES', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.COBRANZA_ASIGNACIONES
    (
        IDASIGNACION       INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        IDCAB              INT NULL,
        IDGENERADAS        INT NULL,
        IDCOBRADOR         INT NOT NULL,
        IDUSUARIO_REGISTRO INT NOT NULL,
        FECHA_ASIGNACION   DATETIME NOT NULL CONSTRAINT DF_COBRANZA_ASIGNACIONES_FECHA DEFAULT(GETDATE()),
        ACTIVO             BIT NOT NULL CONSTRAINT DF_COBRANZA_ASIGNACIONES_ACTIVO DEFAULT(1)
    );

    CREATE INDEX IX_COBRANZA_ASIGNACIONES_CAB
        ON dbo.COBRANZA_ASIGNACIONES (IDCAB, ACTIVO, FECHA_ASIGNACION DESC);

    CREATE INDEX IX_COBRANZA_ASIGNACIONES_CUOTA
        ON dbo.COBRANZA_ASIGNACIONES (IDGENERADAS, ACTIVO, FECHA_ASIGNACION DESC);

    CREATE INDEX IX_COBRANZA_ASIGNACIONES_COBRADOR
        ON dbo.COBRANZA_ASIGNACIONES (IDCOBRADOR, ACTIVO, FECHA_ASIGNACION DESC);

    CREATE UNIQUE INDEX UX_COBRANZA_ASIGNACIONES_CAB_ACTIVA
        ON dbo.COBRANZA_ASIGNACIONES (IDCAB)
        WHERE ACTIVO = 1 AND IDGENERADAS IS NULL;

    CREATE UNIQUE INDEX UX_COBRANZA_ASIGNACIONES_CUOTA_ACTIVA
        ON dbo.COBRANZA_ASIGNACIONES (IDGENERADAS)
        WHERE ACTIVO = 1 AND IDGENERADAS IS NOT NULL;
END
