SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID('dbo.DESCUENTOS_CUOTA', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DESCUENTOS_CUOTA
    (
        IDDESCUENTO         INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        IDGENERADAS         INT NOT NULL,
        MONTO               DECIMAL(12,0) NOT NULL,
        MOTIVO              VARCHAR(200) NULL,
        NRO_NOTA_CREDITO    VARCHAR(30) NULL,
        ID_USUARIO_CREADOR  INT NOT NULL,
        FECHA_CREACION      DATETIME NOT NULL CONSTRAINT DF_DESCUENTOS_CUOTA_FECHA DEFAULT(GETDATE()),
        APLICADO            BIT NOT NULL CONSTRAINT DF_DESCUENTOS_CUOTA_APLICADO DEFAULT(0),
        FECHA_APLICADO      DATETIME NULL,
        ID_USUARIO_APLICO   INT NULL,
        ANULADO             BIT NOT NULL CONSTRAINT DF_DESCUENTOS_CUOTA_ANULADO DEFAULT(0)
    );

    CREATE INDEX IX_DESCUENTOS_CUOTA_GENERADAS
        ON dbo.DESCUENTOS_CUOTA (IDGENERADAS, APLICADO, ANULADO);

    -- Como máximo un descuento pendiente (no aplicado, no anulado) por cuota — evita que
    -- se acumulen dos descuentos vivos sobre la misma cuota por error de carga duplicada.
    CREATE UNIQUE INDEX UX_DESCUENTOS_CUOTA_PENDIENTE
        ON dbo.DESCUENTOS_CUOTA (IDGENERADAS)
        WHERE APLICADO = 0 AND ANULADO = 0;
END
