-- ============================================================
-- ÍNDICES CREDISOFT — optimización de consultas frecuentes
-- Compatible: SQL Server 2008 R2 y superior
-- Cada índice usa IF NOT EXISTS para ser reutilizable sin error
-- ============================================================

USE CREDISOFT;
GO

-- ── ARTICULOS ────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ARTICULOS_ES_D' AND object_id = OBJECT_ID('ARTICULOS'))
    CREATE INDEX IX_ARTICULOS_ES_D ON ARTICULOS (ES, D) INCLUDE (CA, IDM, MAXCUOTA, SLC);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ARTICULOS_CA' AND object_id = OBJECT_ID('ARTICULOS'))
    CREATE INDEX IX_ARTICULOS_CA ON ARTICULOS (CA) INCLUDE (D, ES, IDM);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ARTICULOS_D' AND object_id = OBJECT_ID('ARTICULOS'))
    CREATE INDEX IX_ARTICULOS_D ON ARTICULOS (D) INCLUDE (CA, ES, IDM, MAXCUOTA, SLC);
GO

-- ── PRICES ───────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PRICES_IDART_IDLOCAL' AND object_id = OBJECT_ID('PRICES'))
    CREATE INDEX IX_PRICES_IDART_IDLOCAL ON PRICES (IDART, IDLOCAL, DELETADO) INCLUDE (S, PC, PVENTA, CONTADO, PPROMO);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PRICES_IDLOCAL_DELETADO' AND object_id = OBJECT_ID('PRICES'))
    CREATE INDEX IX_PRICES_IDLOCAL_DELETADO ON PRICES (IDLOCAL, DELETADO) INCLUDE (IDART, S, PC, PVENTA, CONTADO);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PRICES_DELETADO_IDART' AND object_id = OBJECT_ID('PRICES'))
    CREATE INDEX IX_PRICES_DELETADO_IDART ON PRICES (DELETADO, IDART) INCLUDE (S, PVENTA, CONTADO);
GO

-- ── CLIENTES ─────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CLIENTES_NOMBRE' AND object_id = OBJECT_ID('CLIENTES'))
    CREATE INDEX IX_CLIENTES_NOMBRE ON CLIENTES (NOMBRE_CLIENTE) INCLUDE (ID_CLIENTE, CI_CLIENTE, ESTADO, LOCAL, CRED_MAX, TELEFONO_CLIENTE, CIUDAD_CLIENTE);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CLIENTES_CI' AND object_id = OBJECT_ID('CLIENTES'))
    CREATE INDEX IX_CLIENTES_CI ON CLIENTES (CI_CLIENTE) INCLUDE (ID_CLIENTE, NOMBRE_CLIENTE, ESTADO);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CLIENTES_ESTADO' AND object_id = OBJECT_ID('CLIENTES'))
    CREATE INDEX IX_CLIENTES_ESTADO ON CLIENTES (ESTADO, LOCAL) INCLUDE (ID_CLIENTE, NOMBRE_CLIENTE, CI_CLIENTE, CRED_MAX);
GO

-- ── GENERADAS (cuotas) ────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_GENERADAS_ESTADO' AND object_id = OBJECT_ID('GENERADAS'))
    CREATE INDEX IX_GENERADAS_ESTADO ON GENERADAS (ESTADO) INCLUDE (IDCAB, IDLOCAL);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_GENERADAS_IDCAB' AND object_id = OBJECT_ID('GENERADAS'))
    CREATE INDEX IX_GENERADAS_IDCAB ON GENERADAS (IDCAB) INCLUDE (ESTADO, IDLOCAL);
GO

-- ── CABECERA_SALES ────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CABECERA_SALES_IDCLIENTE' AND object_id = OBJECT_ID('CABECERA_SALES'))
    CREATE INDEX IX_CABECERA_SALES_IDCLIENTE ON CABECERA_SALES (ID_CLIENTE, ESTADO) INCLUDE (IDCAB, ID_LOCAL);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CABECERA_SALES_ESTADO' AND object_id = OBJECT_ID('CABECERA_SALES'))
    CREATE INDEX IX_CABECERA_SALES_ESTADO ON CABECERA_SALES (ESTADO) INCLUDE (ID_CLIENTE, IDCAB, ID_LOCAL);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CABECERA_SALES_ESTADO_FDV' AND object_id = OBJECT_ID('CABECERA_SALES'))
    CREATE INDEX IX_CABECERA_SALES_ESTADO_FDV ON CABECERA_SALES (ESTADO, FORMA_DE_VENTA) INCLUDE (ID_CLIENTE, DEBE, HABER);
GO

-- ── TRANSFERENCIAS ────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAB_REMITO_TMP_FECHA' AND object_id = OBJECT_ID('CAB_REMITO_TMP'))
    CREATE INDEX IX_CAB_REMITO_TMP_FECHA ON CAB_REMITO_TMP (FECHA) INCLUDE (IDORIGEN, IDDESTINO, ESTADO, IDUENVIO);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CAB_REMITO_ACEPTADO_FECHA' AND object_id = OBJECT_ID('CAB_REMITO_ACEPTADO'))
    CREATE INDEX IX_CAB_REMITO_ACEPTADO_FECHA ON CAB_REMITO_ACEPTADO (FECHA) INCLUDE (IDORIGEN, IDDESTINO, IDREMITO, IDUENVIO, IDURECIBO);
GO

PRINT 'Índices creados correctamente en CREDISOFT.';
GO
